import zipfile
import os

# Create a directory to hold the website files
dir_name = "healthwisdom_website"
os.makedirs(dir_name, exist_ok=True)

# Dictionary of files and their content
web_files = {
"index.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    .hero { background: linear-gradient(135deg, #38ef7d, #11998e); color: #fff; padding: 60px 20px; text-align: center; }\n    .hero h1 { font-size: 2.8rem; margin-bottom: 10px; }\n    .hero input[type=\"text\"] { padding: 12px; width: 40vw; border-radius: 24px; border: none; margin-top: 20px; font-size: 1.2rem; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .cards { display: flex; flex-wrap: wrap; justify-content: center; margin: 40px 0; gap: 18px;}\n    .card { background: #fff; color: #333; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07); padding: 30px; width: 270px; }\n    @media (max-width: 800px) {\n      .cards { flex-direction: column; align-items: center;}\n      .hero input[type=\"text\"] { width: 80vw; }\n    }\n  </style>\n</head>\n<body>\n  <nav>\n    <a href=\"index.html\">Home</a>\n    <a href=\"diseases.html\">Diseases</a>\n    <a href=\"foods.html\">Food Insights</a>\n    <a href=\"tips.html\">Health Tips</a>\n    <a href=\"about.html\">About</a>\n    <a href=\"contact.html\">Contact</a>\n  </nav>\n  <div class=\"hero\">\n    <h1>Unlock Your Health Potential With AI Tips</h1>\n    <p>Personalized advice for every ailment. Trusted guidance for food choices.<br>Search for disease or food item:</p>\n    <input type=\"text\" placeholder=\"e.g. Diabetes, Apple, Hypertension...\">\n  </div>\n  <div class=\"cards\">\n    <div class=\"card\"><h3>Diabetes Care</h3><p>Smart eating, regular exercise, best foods, and medical advice for diabetes.</p></div>\n    <div class=\"card\"><h3>Healthy Foods</h3><p>Benefits & cautions for every food: fruits, vegetables, proteins, snacks, and more.</p></div>\n    <div class=\"card\"><h3>Heart Health Tips</h3><p>Daily habits that support a strong heart, plus practical food swaps.</p></div>\n  </div>\n</body>\n</html>",

"diseases.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>Diseases & Care - HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .container { max-width: 900px; margin: 32px auto; background: #fff; padding: 32px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07);}\n    h1 { color: #11998e; margin-bottom: 24px; }\n    .disease { margin-bottom: 34px; }\n    .disease h2 { margin-top: 0; color: #38ef7d; }\n    .disease ul { margin: 10px 0; }\n    .disclaimer { font-size: 0.95em; color: #666; margin-top: 18px;}\n  </style>\n</head>\n<body>\n<nav>\n  <a href=\"index.html\">Home</a>\n  <a href=\"diseases.html\">Diseases</a>\n  <a href=\"foods.html\">Food Insights</a>\n  <a href=\"tips.html\">Health Tips</a>\n  <a href=\"about.html\">About</a>\n  <a href=\"contact.html\">Contact</a>\n</nav>\n<div class=\"container\">\n  <h1>Disease Guidance & Tips</h1>\n  <div class=\"disease\">\n    <h2>Diabetes</h2>\n    <ul>\n      <li>Eat complex carbs (whole grains, vegetables) instead of refined sugars.</li>\n      <li>Exercise at least 30 minutes per day.</li>\n      <li>Monitor blood sugar regularly; consult your doctor for medication advice.</li>\n      <li><b>Best foods:</b> Leafy greens, berries, lean proteins.</li>\n      <li><b>Limit:</b> Sugary snacks, refined carbs, sweet drinks.</li>\n    </ul>\n  </div>\n  <div class=\"disease\">\n    <h2>Hypertension (High Blood Pressure)</h2>\n    <ul>\n      <li>Reduce salt; flavor with herbs/spices instead.</li>\n      <li>Eat more potassium-rich foods: bananas, spinach, oranges.</li>\n      <li>Physical activities like walking, cycling, swimming help regulate pressure.</li>\n      <li><b>Limit:</b> Processed foods, red meat, excess alcohol.</li>\n    </ul>\n  </div>\n  <div class=\"disease\">\n    <h2>Heart Disease Prevention</h2>\n    <ul>\n      <li>Prioritize omega-3 rich foods: salmon, flaxseeds, walnuts.</li>\n      <li>Swap saturated fats for healthy alternatives (olive oil, nuts, avocado).</li>\n      <li>Maintain an active lifestyle.</li>\n      <li><b>Limit:</b> Deep-fried foods, high-sugar desserts, trans fats.</li>\n    </ul>\n  </div>\n  <div class=\"disclaimer\">\n    <b>Disclaimer:</b> This site gives general advice. Always consult your doctor for personal health issues.\n  </div>\n</div>\n</body>\n</html>",

"foods.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>Food Insights - HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .container { max-width: 900px; margin: 32px auto; background: #fff; padding: 32px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07);}\n    h1 { color: #11998e; margin-bottom: 24px; }\n    table { width: 100%; border-collapse: collapse;}\n    th, td { border: 1px solid #38ef7d55; padding: 10px 8px; text-align: left;}\n    th { background: #38ef7d14; color: #11998e; }\n    tr:nth-child(even) { background: #f6fff6;}\n  </style>\n</head>\n<body>\n<nav>\n  <a href=\"index.html\">Home</a>\n  <a href=\"diseases.html\">Diseases</a>\n  <a href=\"foods.html\">Food Insights</a>\n  <a href=\"tips.html\">Health Tips</a>\n  <a href=\"about.html\">About</a>\n  <a href=\"contact.html\">Contact</a>\n</nav>\n<div class=\"container\">\n  <h1>Food Advantages & Disadvantages</h1>\n  <table>\n    <tr>\n      <th>Food</th>\n      <th>Advantages</th>\n      <th>Disadvantages</th>\n    </tr>\n    <tr>\n      <td>Apple</td>\n      <td>Rich in fiber & vitamins, good for digestion</td>\n      <td>Can quickly raise blood sugar for diabetics</td>\n    </tr>\n    <tr>\n      <td>Spinach</td>\n      <td>High in iron, vitamin K, calcium</td>\n      <td>Oxalates may reduce calcium absorption</td>\n    </tr>\n    <tr>\n      <td>Chicken</td>\n      <td>High protein, low fat (if grilled/skinless)</td>\n      <td>Fried/processed forms add unhealthy fat/salt</td>\n    </tr>\n    <tr>\n      <td>Rice</td>\n      <td>Fast energy, gluten-free</td>\n      <td>White rice is low-fiber, can affect sugar</td>\n    </tr>\n    <tr>\n      <td>Soda</td>\n      <td>Quick energy boost, enjoyable taste</td>\n      <td>High sugar, no nutrients, increases diabetes risk</td>\n    </tr>\n  </table>\n</div>\n</body>\n</html>",

"tips.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>Health Tips - HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .container { max-width: 800px; margin: 32px auto; background: #fff; padding: 32px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07);}\n    h1 { color: #11998e; margin-bottom: 24px; }\n    ul { margin-bottom: 24px; }\n  </style>\n</head>\n<body>\n<nav>\n  <a href=\"index.html\">Home</a>\n  <a href=\"diseases.html\">Diseases</a>\n  <a href=\"foods.html\">Food Insights</a>\n  <a href=\"tips.html\">Health Tips</a>\n  <a href=\"about.html\">About</a>\n  <a href=\"contact.html\">Contact</a>\n</nav>\n<div class=\"container\">\n  <h1>General Health Tips</h1>\n  <ul>\n    <li>Drink at least 6-8 glasses of water each day.</li>\n    <li>Eat a diverse diet: fruits, veggies, whole grains, proteins.</li>\n    <li>Exercise daily: 30 minutes of activity is recommended.</li>\n    <li>Get 7-9 hours of sleep every night.</li>\n    <li>Avoid sugary snacks and limit junk food.</li>\n    <li>Minimize stress through meditation or hobbies.</li>\n    <li>Don’t skip annual health checkups.</li>\n    <li>Proper hand hygiene protects against many illnesses.</li>\n    <li>Use sunscreen when outdoors to protect your skin.</li>\n    <li>Limit screens before bed for better sleep quality.</li>\n  </ul>\n</div>\n</body>\n</html>",

"about.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>About Us - HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .container { max-width: 800px; margin: 32px auto; background: #fff; padding: 32px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07);}\n    h1 { color: #11998e; margin-bottom: 24px; }\n  </style>\n</head>\n<body>\n<nav>\n  <a href=\"index.html\">Home</a>\n  <a href=\"diseases.html\">Diseases</a>\n  <a href=\"foods.html\">Food Insights</a>\n  <a href=\"tips.html\">Health Tips</a>\n  <a href=\"about.html\">About</a>\n  <a href=\"contact.html\">Contact</a>\n</nav>\n<div class=\"container\">\n  <h1>About HealthWisdom</h1>\n  <p>\n    HealthWisdom empowers you with easy-to-understand health advice, expert diet information, and practical tips powered by AI. We combine scientific research with technological innovation to help you make informed choices every day.\n  </p>\n  <p>\n    <b>Our Mission:</b> To make healthy living simple, accessible, and effective for everyone.\n  </p>\n  <p>\n    <b>Vision:</b> Building a healthier world with AI-driven personalized wellness for all.\n  </p>\n  <p>\n    <b>Note:</b> Always consult your healthcare provider for individual advice.\n  </p>\n</div>\n</body>\n</html>",

"contact.html": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n  <title>Contact Us - HealthWisdom</title>\n  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n  <style>\n    body { font-family: Arial, background: #f6fff6; margin: 0; }\n    nav { background: #ffffffcc; padding: 12px 0; box-shadow: 0 2px 8px rgba(56, 239, 125, 0.15); position: sticky; top: 0; }\n    nav a { color: #11998e; margin: 0 18px; text-decoration: none; font-weight: bold; font-size: 1.15rem; }\n    .container { max-width: 800px; margin: 32px auto; background: #fff; padding: 32px; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.07);}\n    h1 { color: #11998e; margin-bottom: 24px; }\n    form { display: flex; flex-direction: column; gap: 16px; width: 100%; max-width: 400px;}\n    input, textarea { padding: 12px; border-radius: 8px; border: 1px solid #38ef7d55;}\n    button { background: #38ef7d; color: #fff; border: none; padding: 13px; border-radius: 8px; font-size: 1.1rem; cursor: pointer;}\n    button:hover { background: #11998e; }\n  </style>\n</head>\n<body>\n<nav>\n  <a href=\"index.html\">Home</a>\n  <a href=\"diseases.html\">Diseases</a>\n  <a href=\"foods.html\">Food Insights</a>\n  <a href=\"tips.html\">Health Tips</a>\n  <a href=\"about.html\">About</a>\n  <a href=\"contact.html\">Contact</a>\n</nav>\n<div class=\"container\">\n  <h1>Contact Us</h1>\n  <p>\n    Have questions, suggestions, or need advice? Reach out below!\n  </p>\n  <form>\n    <input type=\"text\" placeholder=\"Your Name\" required>\n    <input type=\"email\" placeholder=\"Your Email\" required>\n    <textarea placeholder=\"Your message...\" rows=\"5\" required></textarea>\n    <button type=\"submit\">Send Message</button>\n  </form>\n</div>\n</body>\n</html>"
}

# Write all HTML files
for filename, content in web_files.items():
    with open(os.path.join(dir_name, filename), 'w', encoding='utf-8') as f:
        f.write(content)

# Create a zip archive of the website folder
zip_filename = "healthwisdom_website.zip"
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files in os.walk(dir_name):
        for file in files:
            zipf.write(os.path.join(root, file), arcname=file)

zip_filename
